# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json tsconfig.json ./
COPY src ./src
RUN npm install && npm run build

# Production stage
FROM node:lts-alpine
WORKDIR /app

# Install only production dependencies
COPY package.json ./
RUN npm install --production

# Copy build artifacts
COPY --from=builder /app/dist ./dist

# Command to run
CMD ["node", "dist/index.js"]
